amcl:
  ros__parameters:
    use_sim_time: True              # Dùng thời gian giả lập (True nếu chạy Gazebo, False nếu chạy thực tế)
    alpha1: 0.2                     # Sai số quay theo trục z (odom yaw)
    alpha2: 0.2                     # Sai số dịch chuyển khi có quay
    alpha3: 0.2                     # Sai số dịch chuyển thẳng (odom x, y)
    alpha4: 0.2                     # Sai số quay khi có dịch chuyển
    alpha5: 0.2                     # Sai số bổ sung (tùy loại odom)
    base_frame_id: "base_link"      # Frame gốc của robot (gắn IMU, odom,…)
    beam_skip_distance: 0.5         # Khoảng cách cho phép bỏ qua beam (m)
    beam_skip_error_threshold: 0.9  # Ngưỡng lỗi khi beam bị bỏ qua
    beam_skip_threshold: 0.3        # Tỉ lệ beam bỏ qua tối đa
    do_beamskip: false              # Có bỏ qua beam khi scan không
    global_frame_id: "map"          # Frame bản đồ toàn cục
    lambda_short: 0.1               # Tham số cho model z_short (tia laser bị chặn ngắn hơn dự kiến)
    laser_likelihood_max_dist: 2.0  # Khoảng cách tối đa cho đánh giá xác suất từ laser
    laser_max_range: 100.0          # Tầm xa tối đa của laser
    laser_min_range: -1.0           # Tầm gần tối thiểu (-1 = mặc định theo sensor)
    laser_model_type: "likelihood_field"  # Model dùng cho matching scan ("beam" hoặc "likelihood_field")
    max_beams: 60                   # Số lượng tia laser dùng cho localization
    max_particles: 2000             # Số hạt tối đa (Monte Carlo localization)
    min_particles: 500              # Số hạt tối thiểu
    odom_frame_id: "odom"           # Frame quán tính của robot (odom)
    pf_err: 0.05                    # Sai số ước lượng hạt cho resampling
    pf_z: 0.99                      # Ngưỡng xác suất cho resampling
    recovery_alpha_fast: 0.0        # Tham số khôi phục localization nhanh
    recovery_alpha_slow: 0.0        # Tham số khôi phục localization chậm
    resample_interval: 1            # Số lần cập nhật trước khi resample hạt
    robot_model_type: "nav2_amcl::OmniMotionModel" # Mô hình chuyển động (diff drive hoặc omni)
    save_pose_rate: 0.5             # Tần suất lưu pose xuống file (Hz)
    sigma_hit: 0.2                  # Độ lệch chuẩn cho model z_hit (tia laser khớp vật cản)
    tf_broadcast: true              # Có broadcast TF map->odom không
    transform_tolerance: 1.0        # Độ trễ TF cho phép (giây)
    update_min_a: 0.2               # Góc quay tối thiểu để update AMCL (rad)
    update_min_d: 0.25              # Khoảng cách tối thiểu để update AMCL (m)
    z_hit: 0.5                      # Tỉ lệ model z_hit
    z_max: 0.05                     # Tỉ lệ model z_max (tia vượt ngoài range)
    z_rand: 0.5                     # Tỉ lệ model z_rand (tia random noise)
    z_short: 0.05                   # Tỉ lệ model z_short (tia chặn ngắn hơn dự kiến)
    scan_topic: /scan               # Topic laser
    set_initial_pose: true          # Có set initial pose mặc định không
    initial_pose:                   # Pose ban đầu của robot (nếu không set qua RViz)
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0


amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_smooth_path_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_drive_on_heading_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_globally_updated_goal_condition_bt_node
    - nav2_is_path_valid_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_truncate_path_local_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_path_expiring_timer_condition
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node
    - nav2_controller_cancel_bt_node
    - nav2_path_longer_on_approach_bt_node
    - nav2_wait_cancel_bt_node
    - nav2_spin_cancel_bt_node
    - nav2_back_up_cancel_bt_node
    - nav2_drive_on_heading_cancel_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: True

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.9       # Vận tốc ngang toi thiểu
    min_theta_velocity_threshold: 0.001   # Vận tốc góc tối thiểu
    failure_tolerance: 0.3          # Ngưỡng thất bại (phần trăm thời gian không có lệnh điều khiển)
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2   # Bán kính tối thiểu để coi là có di chuyển (m)
      movement_time_allowance: 10.0   # Thời gian tối đa không di chuyển trước khi báo lỗi (giây)
    # Goal checker parameters
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25      # Khoảng cách tối thiểu để coi là đạt mục tiêu (m)
      yaw_goal_tolerance: 0.5    # Góc tối thiểu để coi là đạt mục tiêu (rad)
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.30        # Vận tốc tiến tối đa theo trục x (m/s)
      max_vel_y: 0.0
      max_vel_theta: 1.0     # Vận tốc góc tối đa (rad/s)
      min_speed_xy: 0.0       
      max_speed_xy: 0.30    # Vận tốc tổng hợp tối đa theo xy (m/s)
      min_speed_theta: 0.0   #không bắt buộc phải có tốc độ quay tối thiểu (robot có thể đứng yên khi quay).
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 20         # Số mẫu vận tốc theo trục x
      vy_samples: 5          # Số mẫu vận tốc theo trục y  
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.4
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0     #Giá trị nhỏ → gradient mượt hơn, vùng nguy hiểm loang xa hơn.
        inflation_radius: 0.3        #Bán kính vùng nguy hiểm (m)
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 1.5
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 0.4
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 1.5
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0    #Giá trị nhỏ → gradient mượt hơn, vùng nguy hiểm loang xa hơn.
        inflation_radius: 0.3     #Bán kính vùng nguy hiểm (m)  
      always_send_full_costmap: True

map_server:
  ros__parameters:
    use_sim_time: True
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: True
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: True

waypoint_follower:
  ros__parameters:
    use_sim_time: True
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: True
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.26, 0.0, 1.0]
    min_velocity: [-0.26, 0.0, -1.0]
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0